application: amadeo-traintime
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /index\.html
  static_files: index.html
  upload: index.html
- url: /assets/js
  static_dir: assets/js
- url: /assets/css
  static_dir: assets/css
- url: /assets/select2
  static_dir: assets/select2
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: server.app